# The URL the site will be built for
base_url = "https://roboticfox.io"

taxonomies = [
    {name = "tags"}
]


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "terminimal"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo_text = "NuclearWinter's blog"
# Put all your custom variables here
accent_color = "blue"
background_color = "dark"
author = "NuclearWinter"

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "blog", url = "$BASE_URL"},
    
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about me", url = "$BASE_URL/about"},
    
    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/Nukeuler123", newtab = true},
]

enable_post_view_navigation = true

post_view_navigation_prompt = "Read more"
use_full_hack_font = true
page_titles = "combined"
